[package]
name = "hdpi_blinkenwall"
version = "0.1.0"
authors = ["Andreas Monitzer <metalab@monitzer.com>"]

[dependencies]
log = "0.3"
env_logger = "0.4"
glium = "*"
glutin = "*"
chrono = "0.3"
ws = "0.6"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
mpv = "0.2"
git2 = "0.6"
