[package]
name = "hdpi_blinkenwall"
version = "0.1.0"
authors = ["Andreas Monitzer <metalab@monitzer.com>"]

[dependencies]
log = "0.3"
env_logger = "0.4"
glium = "*"
glutin = "*"
chrono = "0.3"
ws = "0.6"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
mpv = "0.2"
git2 = "0.6"
uuid = { version = "0.5", features = ["v4"] }
portaudio = "0.7"
atomic_ring_buffer = "1.0"
rustfft = "2.0"
bdf = "0.5"
palette = "0.2"
rand = "0.3"
unicode-normalization = "0.1"
