# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console

  # An appender named "requests" that writes to a file with a custom pattern encoder
  file:
    kind: file
    path: "blinkenwall.log"
    encoder:
      pattern: "{d} [{f}:{L}] {l} - {h({m})}{n}"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: warn
  appenders:
    - file
    - stdout

loggers:
  # Raise the maximum log level for events sent to the "hdpi_blinkenwall" logger to "info"
  hdpi_blinkenwall:
    level: debug
